server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Cache and serve static files
    location ~* \.(?:js|css|png|jpg|jpeg|gif|ico|json|svg)$ {
        try_files $uri =404;
        expires 1y;
        add_header Cache-Control "public, immutable";
        add_header Access-Control-Allow-Origin "*";
    }

    # SPA fallback for React Router
    location / {
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "no-cache";
    }

    # Enable gzip
    gzip on;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml;
}
