apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-secrets
type: Opaque
stringData:
  mongo-uri: {{ .Values.env.MONGO_URI | quote }}
  jwt-secret: {{ .Values.env.JWT_SECRET | quote }}
