replicaCount: 2

image:
  repository: millyanne93/planit-frontend
  tag: "1.9"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 80

resources: {}

# Environment variables passed into the frontend container
env:
  API_BASE_URL: "http://localhost/api"
# Ingress configuration
ingress:
  enabled: false
  className: "nginx"
  annotations: {}
  hosts: []
  tls: []

# Reference to backend service (for ingress path routing)
backend:
  servicePort: 5000
