replicaCount: 2

image:
  repository: millyanne93/planit-frontend
  tag: "1.10"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 80

resources: {} 
# Ingress configuration
ingress:
  enabled: false
  className: "nginx"
  annotations: {}
  hosts: []
  tls: []

# Reference to backend service (for ingress path routing)
backend:
  servicePort: 5000
